name: device_platform_uid
description: "get device UUID"
version: 1.0.3
homepage: https://github.com/deepak07082/device_id.git

topics:
  - device_id
  - platform_id
  - UUID

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.2


flutter:
  plugin:
    platforms:
      android:
        package: com.example.device_id
        pluginClass: DeviceIdPlugin
      ios:
        pluginClass: DeviceIdPlugin
